name: Build and Publish Validator Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Build the validator binaries
      - name: Build Validator
        run: |
          mkdir -p /tmp/validator-release
          ./scripts/cargo-install-all.sh --validator-only /tmp/validator-release

      # Package the build output
      - name: Package Release
        run: |
          cd /tmp/validator-release
          tar -czvf validator-release.tar.gz bin/
          mv validator-release.tar.gz $GITHUB_WORKSPACE/

      # Upload the artifact as a release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: validator-release.tar.gz
          asset_name: validator-release-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
